apiVersion: v1
kind: Service
metadata:
  labels:
    app: giropops
  name: giropops
  namespace: terasaka
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32555
    name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: giropops
  sessionAffinity: None
  type: NodePort
